import Head from 'next/head';
import Landing from '../components/Landing';
import { store } from '../store/store';
import { Provider } from 'react-redux';
import setScrollEventListener from '../functions/setScrollEventListener';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    setScrollEventListener();
  }, []);

  return (
    <>
      <Provider store={store}>
        <Head>
          <title>Webtronics | Frontend developer</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
        </Head>
        <Landing />
      </Provider>
    </>
  )
}
